[theme]
primaryColor = "#6366F1"
backgroundColor = "#090D16"
secondaryBackgroundColor = "#0F172A"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
